name: Build Kernel

env:
  TZ: Asia/Shanghai
  ANDROID_VERSION: 'android12'
  KERNEL_VERSION: '5.10'
  KERNEL_NAME: 'localhost-Hutao'

on:
  workflow_dispatch:
    inputs:
      stock_config:
        description: '是否伪装defconfig为原厂defconfig'
        required: true
        type: boolean
        default: false
      better_net:
        description: '是否开启网络功能拓展配置(用于为ipset及需要iptables等高级网络功能内核支持的程序提供支持)'
        required: true
        type: boolean
        default: false
      droidspaces:
        description: "Droidspaces 容器支持"
        required: false
        type: choice
        options:
          - "off"
          - "678"
          - "123"
          - "345"
        default: "off"
      lxc:
        description: '是否启用lxc支持(部分设备可能不开机)'
        required: true
        type: boolean
        default: false
      baseband_guard:
        description: '是否开启内核级基带保护(阻止一切对非用户分区的写入，有效防止格机)'
        required: true
        type: boolean
        default: true
      lto_none:
        description: '是否关闭LTO优化(测试性；大幅提升编译速度)'
        required: true
        type: boolean
        default: true
      tmpfs:
        description: '是否开启对于mountify 的支持'
        required: true
        type: boolean
        default: true
      ccache_update:
        description: '更新ccache缓存(将本次编译生成的ccache缓存覆盖至仓库缓存，在更改编译配置、源码或需要刷新缓存时开启)'
        required: true
        type: boolean
        default: false
      ccache_debug:
        description: '是否上传 Ccache调试日志(用于调试, 无需要不必开启)'
        required: true
        type: boolean
        default: false


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: 初始化源码仓库及llvm-Clang工具链
        run: |
          mkdir -p kernel_workspace
          cd kernel_workspace
          
          # 安装配置环境依赖
          sudo apt-mark hold firefox &&
          sudo apt-mark hold libc-bin &&
          sudo apt purge man-db &&
          sudo rm -rf /var/lib/man-db/auto-update &&
          sudo apt update &&
          sudo apt-get install -y --no-install-recommends \
            curl bison flex make binutils git perl gcc python3 \
            python-is-python3 bc libssl-dev libelf-dev \
            bc aria2 zip unzip binutils-aarch64-linux-gnu &
          
          #使用最新版ccache-ECS（特化优化内核编译缓存，大幅提升二次不同配置编译速度）
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/ccache-x86-64 -O ccache &&
          sudo cp -f ./ccache /usr/bin/ccache &&
          sudo chmod +x /usr/bin/ccache &&
          rm -f ./ccache &
          
          echo "正在克隆源码仓库..." &&
          aria2c -s16 -x16 -k1M https://github.com/ESK-Project/android12-5.10-gki/archive/refs/heads/main.zip -o common.zip && 
          unzip -q common.zip && 
          mv "android12-5.10-gki-main" common &&
          rm -rf common.zip &
          
          echo "正在克隆llvm-Clang20工具链..." &&
          mkdir -p clang20 &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang20-r547379/clang-r547379.zip -o clang.zip &&
          unzip -q clang.zip -d clang20 &&
          rm -rf clang.zip &
          
          echo "正在克隆构建工具..." &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang20-r547379/build-tools.zip -o build-tools.zip &&
          unzip -q build-tools.zip &&
          rm -rf build-tools.zip &
          
          wait
          echo "所有源码及llvm-Clang20工具链初始化完成！"
          echo "正在去除 ABI 保护 & 去除 dirty 后缀..."
          rm common/android/abi_gki_protected_exports_* || true
          for f in common/scripts/setlocalversion; do
            sed -i 's/ -dirty//g' "$f"
            sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$f"
          done

      - name: Fetch config script
        run: |
          curl -fLSs "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/scripts/config.sh" -o /tmp/config.sh
          chmod +x /tmp/config.sh
          
      - name: 配置ccache目录
        run: |
          echo "CCACHE_DIR=$HOME/.ccache_${{ env.KERNEL_VERSION }}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=3G" >> $GITHUB_ENV
          echo "当前磁盘空间："
          df -h
          echo "当前构建内核版本：${{ env.KERNEL_VERSION }}"

      - name: 载入当前版本内核的 ccache缓存
        uses: actions/cache@v4
        id: ccache-restore
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-esk-${{ env.KERNEL_VERSION }}
          restore-keys: |
            ccache-esk-${{ env.KERNEL_VERSION }}


      - name: 清除旧 ccache 缓存
        if: inputs.ccache_update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "正在清除仓库中的旧 ccache 缓存..."
          if gh cache delete ccache-esk-${{ env.KERNEL_VERSION }} -R ${{ github.repository }}; then
            echo "成功删除旧的 ccache 缓存！"
          else
            echo "旧缓存不存在或已被清理！"
          fi

      - name: 初始化并配置 ccache
        run: |
          export CCACHE_COMPILERCHECK="none"
          export CCACHE_BASEDIR="${{ github.workspace }}"
          export CCACHE_NOHASHDIR="true"
          export CCACHE_NOHARDLINK="true"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="${{ env.CCACHE_MAXSIZE }}"
          
          mkdir -p "$CCACHE_DIR"
          
          echo "配置ccache缓存大小为: $CCACHE_MAXSIZE"
          ccache -M "$CCACHE_MAXSIZE"
          ccache -o compression=true
          
          echo "ccache初始状态:"
          ccache -s
          
          # 如果缓存恢复命中，显示详细信息
          if [ "${{ steps.ccache-restore.outputs.cache-hit }}" == true ]; then
            echo "ccache缓存命中详情:"
            ccache -sv
          fi

      - name: 启用stock config
        if: inputs.stock_config
        run: |
          cd kernel_workspace/common
          echo "下载相关文件"
          curl -fLSs "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/patches/stock_config.patch" -o stock_config.patch
          patch -p1 --fuzz=3 < stock_config.patch

      - name: 添加lxc
        if: inputs.lxc
        run: |
          cd kernel_workspace/common
          echo "下载相关文件"
          curl -fLSs "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/patches/lxc.patch" -o lxc.patch
          echo "开始patch"
          if [ -e "drivers/gpu/mediatek/mali-valhall/gpu/arm/midgard/context/mali_kbase_context.c" ]; then
            patch -p1 --forward --fuzz=3 < lxc.patch
          else
            sed -i '/^diff --git.*mali_kbase_context\.c$/,/^diff --git/{
              /^diff --git/!d
            }'  lxc.patch
            patch -p1 --forward --fuzz=3 < lxc.patch
          fi
          
      - name: 支持mountify/hybrid的tmpfs模式
        if: inputs.tmpfs
        run: |
          source /tmp/config.sh
          config --enable CONFIG_TMPFS_XATTR
          config --enable CONFIG_TMPFS_POSIX_ACL

      - name: 杂项设置
        run: |
          cd kernel_workspace/common
          sed -i 's/check_defconfig//' ./build.config.gki
          curl -fLSs "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/patches/memblock.patch" -o memblock.patch
          patch -p1 --fuzz=3 < memblock.patch

      - name: 关闭LTO
        if: inputs.lto_none
        run: |
          source /tmp/config.sh
          config --disable CONFIG_ARCH_SUPPORTS_LTO_CLANG
          config --disable CONFIG_ARCH_SUPPORTS_LTO_CLANG_THIN
          config --disable CONFIG_LTO_CLANG_THIN
          config --disable CONFIG_LTO_CLANG_FULL
          config --enable CONFIG_LTO_NONE

      - name: 启用网络功能增强优化配置
        if: inputs.better_net
        run: |
          source /tmp/config.sh
          #启用  BPF 流解析器,实现高性能网络流量处理,增强网络监控和分析能力
          config --enable CONFIG_BPF_STREAM_PARSER
          #开启增强 Netfilter 防火墙扩展模块,支持基于地址类型的匹配规则,启用 IP 集合支持,提高防火墙规则灵活性,支持更复杂的流量过滤策略
          config --enable CONFIG_NETFILTER_XT_MATCH_ADDRTYPE
          config --enable CONFIG_NETFILTER_XT_SET
          #启用 IP 集框架及其多种数据结构实现,提供高效的大规模 IP 地址管理,提高防火墙规则处理效率,减少内存占用
          config --enable CONFIG_IP_SET
          config --set-val CONFIG_IP_SET_MAX 65534
          config --enable CONFIG_IP_SET_BITMAP_IP
          config --enable CONFIG_IP_SET_BITMAP_IPMAC
          config --enable CONFIG_IP_SET_BITMAP_PORT
          config --enable CONFIG_IP_SET_HASH_IP
          config --enable CONFIG_IP_SET_HASH_IPMARK
          config --enable CONFIG_IP_SET_HASH_IPPORT
          config --enable CONFIG_IP_SET_HASH_IPPORTIP
          config --enable CONFIG_IP_SET_HASH_IPPORTNET
          config --enable CONFIG_IP_SET_HASH_IPMAC
          config --enable CONFIG_IP_SET_HASH_MAC
          config --enable CONFIG_IP_SET_HASH_NETPORTNET
          config --enable CONFIG_IP_SET_HASH_NET
          config --enable CONFIG_IP_SET_HASH_NETNET
          config --enable CONFIG_IP_SET_HASH_NETPORT
          config --enable CONFIG_IP_SET_HASH_NETIFACE
          config --enable CONFIG_IP_SET_LIST_SET
          #启用 IPv6 网络地址转换
          config --enable CONFIG_IP6_NF_NAT
          config --enable CONFIG_IP6_NF_TARGET_MASQUERADE
          #由于部分机型的vintf兼容性检测规则，在开启CONFIG_IP6_NF_NAT后开机会出现"您的设备内部出现了问题。请联系您的设备制造商了解详情。"的提示，故添加一个配置修复补丁，在编译内核时隐藏CONFIG_IP6_NF_NAT=y但不影响对应功能编译
          if [[ "${{ inputs.STOCK_CONFIG }}" != "true" ]]; then
            cd kernel_workspace/common
            wget https://github.com/cctv18/oppo_oplus_realme_sm8650/raw/refs/heads/main/other_patch/config.patch
            patch -p1 -F 3 < config.patch || true
          fi

      - name: 集成 Droidspaces 支持
        if: inputs.droidspaces != 'off'
        run: |
          source /tmp/config.sh
          cd kernel_workspace/common
          git clone --depth 1 https://github.com/ravindu644/Droidspaces-OSS.git droidspaces

          SLOT="${{ inputs.droidspaces }}"
          # 678 -> 6_7_8, 123 -> 1_2_3, 345 -> 3_4_5
          SLOT_NAME=$(echo "$SLOT" | sed 's/\(.\)/\1_/g; s/_$//')
          echo "应用 Droidspaces SYSVIPC kABI 修复补丁 (槽位: $SLOT / $SLOT_NAME)..."
          patch -p1 --forward < "droidspaces/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/001.GKI-below-6.12-fix_sysvipc_kabi_${SLOT_NAME}.patch"

        
          echo "应用 Droidspaces POSIX_MQUEUE kABI 修复补丁 (5.10)..."
          patch -p1 --forward < "droidspaces/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/002.5.10_or_lower_use_android_abi_padding_for_posix_mqueue.patch"
          echo "添加 Droidspaces 内核配置..."

          cd ../../
          # 必要配置
          config --enable CONFIG_SYSVIPC
          config --enable CONFIG_POSIX_MQUEUE
          config --enable CONFIG_IPC_NS
          config --enable CONFIG_PID_NS
          config --enable CONFIG_DEVTMPFS

          echo "Droidspaces 集成完成"

      - name: 启用内核级基带保护
        if: inputs.baseband_guard
        run: |
          echo "正在启用启用内核级基带保护支持…"
          source /tmp/config.sh
          config --enable CONFIG_BBG
          cd kernel_workspace/common
          curl -LSs https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh | bash -s
          sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/lockdown/lockdown,baseband_guard/ } }' security/Kconfig

      - name: 添加制作名称
        run: |
          cd kernel_workspace
          echo "替换内核版本后缀..."
          echo "当前内核版本后缀：${{ env.KERNEL_NAME }}"
          for f in ./common/scripts/setlocalversion; do
            sed -i "\$s|echo \"\\\$res\"|echo \"-${{ env.KERNEL_NAME }}\"|" "$f"
          done
           
      - name: 构建内核
        run: |
          WORKDIR="$(pwd)"
          export PATH="/usr/lib/ccache:$PATH"
          export PATH="$WORKDIR/kernel_workspace/clang20/bin:$PATH"
          export PATH="$WORKDIR/kernel_workspace/build-tools/bin:$PATH"
          CLANG_DIR="$WORKDIR/kernel_workspace/clang20/bin"
          CLANG_VERSION="$($CLANG_DIR/clang --version | head -n 1)"
          LLD_VERSION="$($CLANG_DIR/ld.lld --version | head -n 1)"
          echo "编译器信息:"
          echo "Clang版本: $CLANG_VERSION"
          echo "LLD版本: $LLD_VERSION"
          pahole_version=$(pahole --version 2>/dev/null | head -n1); [ -z "$pahole_version" ] && echo "pahole版本：未安装" || echo "pahole版本：$pahole_version"

          export CCACHE_LOGFILE='${{ github.workspace }}/kernel_workspace/ccache.log'
          export CCACHE_COMPILERCHECK="none"
          export CCACHE_BASEDIR="${{ github.workspace }}"
          export CCACHE_NOHASHDIR="true"
          export CCACHE_NOHARDLINK="true"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="3G"
          export CCACHE_IS_KERNEL_COMPILING="true"
          echo "sloppiness = file_stat_matches,include_file_ctime,include_file_mtime,pch_defines,file_macro,time_macros" >> "$CCACHE_DIR/ccache.conf"

          cd kernel_workspace/common
          
          #在构建内核的同时清除不必要的.NET, Android NDK, Haskell, CodeQL运行库，清理空间且不阻塞后续步骤运行
          sudo rm -rf /usr/share/dotnet &
          sudo rm -rf /usr/local/lib/android &
          sudo rm -rf /opt/ghc &
          sudo rm -rf /opt/hostedtoolcache/CodeQL &
          #删除-fno-integrated-as强制检查
          sed -i 's/-fno-integrated-as//' scripts/Kconfig.include &
          
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" LD="ld.lld" HOSTLD=ld.lld O=out KCFLAGS+=-O2 KCFLAGS+=-Wno-error gki_defconfig &&
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" LD="ld.lld" HOSTLD=ld.lld O=out KCFLAGS+=-O2 KCFLAGS+=-Wno-error Image

          echo "内核编译完成！"
          echo "ccache状态："
          ccache -s
          echo "编译后空间:"
          df -h

      - name: 保存新的 ccache 缓存
        if: inputs.ccache_update || steps.ccache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-esk-${{ env.KERNEL_VERSION }}
         
      - name: 克隆 AnyKernel3 并打包
        run: |
          cd kernel_workspace
          git clone https://github.com/Tools-cx-app/AnyKernel3.git --depth=1
          rm -rf ./AnyKernel3/.git
          cd AnyKernel3
          cp ../common/out/arch/arm64/boot/Image ./Image
          if [[ ! -f ./Image ]]; then
            echo "未找到内核镜像文件，构建可能出错"
            exit 1
          fi
          zip -r ../AnyKernel3.zip ./*

      - name: 上传到 Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_CI_SESSION: ${{ secrets.BOT_CI_SESSION }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          STOCK_CONFIG: ${{ inputs.stock_config }}
          LXC: ${{ inputs.lxc }}
          BBG: ${{ inputs.baseband_guard }}
          MOUNTIFY: ${{ inputs.tmpfs }}
          BETTER_NET: ${{ inputs.better_net }}
        run: |
          if [ -z ${{ secrets.BOT_TOKEN }} ]; then
            exit 0
          fi
          pip3 install telethon
          curl -fLSs "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/bot.py" -o bot.py
          python3 bot.py ./kernel_workspace/AnyKernel3.zip

      - name: 上传 Ccache 调试日志
        if: always() && inputs.ccache_debug
        uses: actions/upload-artifact@v4
        with:
          name: ccache-debug-log
          path: ${{ github.workspace }}/kernel_workspace/ccache.log

      - name: 上传 ZIP 工件
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3
          path: ${{ github.workspace }}/kernel_workspace/*.zip
